export const BALANCED_NODE_OMIT_KEYS = [
  'id',
  'locked',
  'constraints',
  'layoutGrow',
  'layoutAlign',
  'mainComponentId',
  'textAutoResize',
  'textAlignVertical',
  'clipsContent',
] as const

export const EFFICIENT_NODE_OMIT_KEYS = [
  'id',
  'locked',
  'visible',
  'blendMode',
  'relativeTransform',
  'reactions',
  'constraints',
  'layoutGrow',
  'layoutAlign',
  'layoutSizingHorizontal',
  'layoutSizingVertical',
  'mainComponentId',
  'mainComponentName',
  'componentProperties',
  'variantProperties',
  'effects',
  'strokes',
  'strokeWeight',
  'rotation',
  'opacity',
  'textAutoResize',
  'textAlignVertical',
  'textAlignHorizontal',
  'clipsContent',
  'paddingTop',
  'paddingRight',
  'paddingBottom',
  'paddingLeft',
  'itemSpacing',
  'primaryAxisAlignItems',
  'counterAxisAlignItems',
  'layoutMode',
  'pointCount',
  'cornerRadius',
] as const
